# Generated by Django 4.2.5 on 2023-12-02 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("assignment1", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="products",
        ),
        migrations.AddField(
            model_name="cart",
            name="products",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="assignment1.product",
            ),
            preserve_default=False,
        ),
    ]
